# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6825d84c35cd380cb430227b6a97354745c39cd746683f17c9a0489a111d248ddbfa22321c42dc7d2a14444ffbe6177a44cfdc7ea7dc15d6cd3f0dbe8b758fde

test:
  secret_key_base: b071383309d923aee1556ca732d818602fe748c84d3e47b36d26af0087ecadd5f7f6c7c650ed0a0680245ec8611aee9f3d9f71a132abb84fcb5dda6dc3ee8f56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
